---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
rabbitmq:
    install: '1'
    user: user
    password: password
    plugins: [rabbitmq_management]
php:
    install: '1'
    ppa: php
    packages: [php7.0-cli, php7.0-intl, php7.0-xdebug, php7.0-dom, php7.0-mbstring, php7.0-bcmath, php7.0-phar]
xdebug:
    install: '1'
composer:
    install: '1'
